// <auto-generated />
using System;
using GeoLog.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NetTopologySuite.Geometries;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace GeoLog.Api.Migrations
{
    [DbContext(typeof(GeoLogDbContext))]
    partial class GeoLogDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.19")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "postgis");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("GeoLog.Api.Data.Entities.RoutePoint", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<Point>("Location")
                        .IsRequired()
                        .HasColumnType("geography(PointZ, 4326)")
                        .HasColumnName("location");

                    b.Property<Guid>("RouteId")
                        .HasColumnType("uuid")
                        .HasColumnName("route_id");

                    b.Property<int>("Sequence")
                        .HasColumnType("integer")
                        .HasColumnName("sequence");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("timestamp");

                    b.HasKey("Id")
                        .HasName("pk_route_points");

                    b.HasIndex("RouteId")
                        .HasDatabaseName("ix_route_points_route_id");

                    b.ToTable("route_points", (string)null);
                });

            modelBuilder.Entity("GeoLog.Api.Data.Entities.RouteStat", b =>
                {
                    b.Property<Guid>("RouteId")
                        .HasColumnType("uuid")
                        .HasColumnName("route_id");

                    b.Property<decimal>("AvgSpeedKmh")
                        .HasColumnType("numeric")
                        .HasColumnName("avg_speed_kmh");

                    b.Property<int>("DurationSeconds")
                        .HasColumnType("integer")
                        .HasColumnName("duration_seconds");

                    b.Property<decimal>("ElevationGainMeters")
                        .HasColumnType("numeric")
                        .HasColumnName("elevation_gain_meters");

                    b.Property<decimal>("ElevationLossMeters")
                        .HasColumnType("numeric")
                        .HasColumnName("elevation_loss_meters");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("end_time");

                    b.Property<DateTime>("LastRecalculatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_recalculated_at");

                    b.Property<decimal>("MaxSpeedKmh")
                        .HasColumnType("numeric")
                        .HasColumnName("max_speed_kmh");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("start_time");

                    b.Property<decimal>("TotalDistanceMeters")
                        .HasColumnType("numeric")
                        .HasColumnName("total_distance_meters");

                    b.HasKey("RouteId")
                        .HasName("pk_route_stats");

                    b.ToTable("route_stats", (string)null);
                });

            modelBuilder.Entity("GeoLog.Api.Data.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AvatarUrl")
                        .HasColumnType("text")
                        .HasColumnName("avatar_url");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("HashedPassword")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("hashed_password");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("username");

                    b.Property<string>("VerificationToken")
                        .HasColumnType("text")
                        .HasColumnName("verification_token");

                    b.Property<DateTime?>("VerifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("verified_at");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("GeoRoute", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<string>("Visibility")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("visibility");

                    b.HasKey("Id")
                        .HasName("pk_routes");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_routes_user_id");

                    b.ToTable("routes", (string)null);
                });

            modelBuilder.Entity("GeoLog.Api.Data.Entities.RoutePoint", b =>
                {
                    b.HasOne("GeoRoute", "GeoRoute")
                        .WithMany("RoutePoints")
                        .HasForeignKey("RouteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_route_points_routes_route_id");

                    b.Navigation("GeoRoute");
                });

            modelBuilder.Entity("GeoLog.Api.Data.Entities.RouteStat", b =>
                {
                    b.HasOne("GeoRoute", "Route")
                        .WithOne("RouteStat")
                        .HasForeignKey("GeoLog.Api.Data.Entities.RouteStat", "RouteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_route_stats_routes_route_id");

                    b.Navigation("Route");
                });

            modelBuilder.Entity("GeoRoute", b =>
                {
                    b.HasOne("GeoLog.Api.Data.Entities.User", "User")
                        .WithMany("Routes")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_routes_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("GeoLog.Api.Data.Entities.User", b =>
                {
                    b.Navigation("Routes");
                });

            modelBuilder.Entity("GeoRoute", b =>
                {
                    b.Navigation("RoutePoints");

                    b.Navigation("RouteStat")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
